apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hk-pwa-backend
  name: hk-pwa-backend
  namespace: oscar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hk-pwa-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hk-pwa-backend
    spec:
      containers:
      - image: bierteam/hk-pwa-backend:master
        envFrom:
        - secretRef:
            name: hk-pwa-env
            optional: false
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 2
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 2
          failureThreshold: 3
          successThreshold: 3
        name: hk-pwa-backend
        resources: {}
      dnsPolicy: ClusterFirst
status:
---
apiVersion: v1
kind: Service
metadata:
  name: hk-pwa-backend
  namespace: oscar
spec:
  selector:
    app: hk-pwa-backend
  ports:
    - port: 80
      name: default
      targetPort: 3000