apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hk-pwa-frontend
  name: hk-pwa-frontend
  namespace: oscar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hk-pwa-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hk-pwa-frontend
    spec:
      containers:
      - image: bierteam/hk-pwa-frontend:master
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 2
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 2
        name: hk-pwa-frontend
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 2
          failureThreshold: 3
          successThreshold: 3
          timeoutSeconds: 2
        resources: {}
      dnsPolicy: ClusterFirst
status:
---
apiVersion: v1
kind: Service
metadata:
  name: hk-pwa-frontend
  namespace: oscar
spec:
  selector:
    app: hk-pwa-frontend
  ports:
    - port: 80
      name: default
      targetPort: 80